### ISSUE TITLE
同时下载多个相册，照片数量多的时候有并发问题

### ISSUE THREAD

**Issue by CatcherX** [facefruit/qzone-assistant-for-windows#1]
下载源码，修改成按原文件名保存，会出现文件名对应的照片不正确。

**Comment by liyonghuan** [comment]
获取相册列表成功，下载相册失败的问题可能是使用的cookie不正确，最好使用h5.qzone.qq.com域名下的cookie比较稳定些。
同时下载多张图片存在并发的问题我也有发现，最近重装系统把本地代码弄没了，不知道是不是没上传最新的代码的问题。最近忙着找工作，这个问题需要迟些再处理，或者你也可以自行处理一下。

**Comment by liyonghuan** [comment]
我看了一下接口返回的数据，好像没有原文件名这个字段吧？

**Comment by CatcherX** [comment]
https://github.com/facefruit/qzone-assistant-for-windows/blob/f70e9e3e5f0ee18f6d5a288d77b22abb5ce17377/QzoneAssistant/QzonePhoto.cs#L20

**Comment by liyonghuan** [comment]
这个字段不能用来作为文件名，这个字段是会重复的。
